config/routes.rb
SmartVending::Application.routes.draw do
  root  :to => 'dashboard#dashboard'
  get "graphics/esolar"
  get "graphics/cnxtrasp"
  get "graphics/psimulado"
  devise_for :users, :skip => [:registrations, :sessions] 
  as :user do
      get '/users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post '/users/sign_in' => 'devise/sessions#create', :as => :user_session
     get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
      delete 'users/:id' => 'devise/registrations#destroy', :as => 'user_destroy_registration'
    end
  resources :machines

  resources :alarms
  match '/:id/alarms', to: 'alarms#index', via: 'get', :as => 'alarms_from'

  resources :customers
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'  
  match '/grid', to: 'static_pages#grid', via: 'get'  

  

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :alarms
  acts_as_gmappable
  def gmaps4rails_address
  "#{nombre_ciudad}, #{provincia}"
  end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  def index
    @machines = Machine.all
    @json = @machines.to_gmaps4rails do |machine, marker|
            marker.infowindow render_to_string(:partial => "/machines/infowindow", :locals => { :machine => machine})
            marker.title "#{machine.category} FieldAgent #{machine.extID}"
#    end
            #marker.picture({:picture => "/assets/powerplant.png",
            marker.picture({:picture => icono_de(machine),
        :width => 32,
        :height => 32})
      #   marker.json({:title => machine.extID})
    end
  end
 
  def icono_de(machine)
    icon = "/assets/"
    if machine.category == 'vending' then
       tipo_de_icono = "market"
    elsif machine.category == 'solar' then
       tipo_de_icono = "solarenergy"
    elsif machine.category == 'recycle' then
       tipo_de_icono = "recycle"
    end
    severidad = "-v"
    machine.alarms.each do |al|
        if al.severity == '2' or al.severity == '3' then
           severidad = "-a"
        elsif al.severity == '4' then
           severidad = "-r"
        end
    end
    icon << tipo_de_icono << severidad << ".png"
  end
  # GET /machines/1
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  def create
    @machine = Machine.new(machine_params)

    if @machine.save
      redirect_to @machine, notice: 'Machine was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /machines/1
  def update
    if @machine.update(machine_params)
      redirect_to @machine, notice: 'Machine was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /machines/1
  def destroy
    @machine.destroy
    redirect_to machines_url, notice: 'Machine was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def machine_params
      params.require(:machine).permit(:extID, :name, :description, :category, :status)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for @machine, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :extID, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :extID, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                machines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/machines/_infowindow.html.erb
<h3><%= machine.name %></h3>
<h4>status: <%= machine.status %></h4>
<div class="well sidebar-nav">
   <ul class="nav nav-list">
      <li class="nav-header"></li>
      <li><a href=<%= alarms_from_path(machine.id) %>> Alarms </a>
      </li>
   </ul>
</div><!--/.well -->

app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/index.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row-fluid">
    <div class="span12">
     <p>
        <%= gmaps4rails(@json) %>
     </p>
    </div><!--/span-->
</div>
<div class="row-fluid">
    <div class="span12">
      <table class="table table-striped">
         <thead>
           <tr>
             <th><%= model_class.human_attribute_name(:extID) %></th>
             <th><%= model_class.human_attribute_name(:name) %></th>
             <th><%= model_class.human_attribute_name(:description) %></th>
             <th><%= model_class.human_attribute_name(:category) %></th>
             <th><%= model_class.human_attribute_name(:status) %></th>
             <th><%=t '.actions', :default => t("helpers.actions") %></th>
           </tr>
         </thead>
         <tbody>
           <% @machines.each do |machine| %>
           <tr>
             <td><%= machine.extID %></td>
             <td><%= machine.name %></td>
             <td><%= machine.description %></td>
             <td><%= machine.category %></td>
             <td><%= machine.status %></td>
             <td>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_machine_path(machine), :class => 'btn btn-mini' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      machine_path(machine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
             </td>
          </tr>
          <% end %>
         </tbody>
      </table>

      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_machine_path,
            :class => 'btn btn-primary' %>
    </div><!--/span-->
</div>

app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row-fluid">
    <div class="span6">
      <p>Aquí va un mapa con las máquinas
        <%= gmaps4rails(@json) %>
        <%= yield :scripts %>
      </p>
    </div><!--/span-->
    <div class="span6">
      <dl class="dl-horizontal">
        <dt><strong><%= model_class.human_attribute_name(:extID) %>:</strong></dt>
        <dd><%= @machine.extID %></dd>
        <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
        <dd><%= @machine.name %></dd>
        <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
        <dd><%= @machine.description %></dd>
        <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
        <dd><%= @machine.category %></dd>
        <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
        <dd><%= @machine.status %></dd>
      </dl>

      <div class="form-actions">
        <%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn'  %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
      </div>
   </div><!--/span-->
</div>