config/routes.rb
SmartVending::Application.routes.draw do
  root  :to => 'dashboard#dashboard'
  get "graphics/esolar"
  get "graphics/cnxtrasp"
  get "graphics/psimulado"
  devise_for :users, :skip => [:registrations, :sessions] 
  as :user do
      get '/users/sign_in' => 'devise/sessions#new', :as => :new_user_session
      post '/users/sign_in' => 'devise/sessions#create', :as => :user_session
     get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
      delete 'users/:id' => 'devise/registrations#destroy', :as => 'user_destroy_registration'
    end
  resources :machines

  resources :alarms
  match '/:id/alarms', to: 'alarms#index', via: 'get', :as => 'alarms_from'

  resources :customers
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'  
  match '/grid', to: 'static_pages#grid', via: 'get'  

  

end

app/views/layouts/_footer.html.erb
<small>
    IAPsolutions Managing Technology <%= link_to " About Us",   about_path %>
 </small>

app/views/layouts/_footer2.html.erb
<footer class="footer text-right">
   <small>
     Powered by <%= link_to image_tag("rails.png", :size =>"30x30", alt:"RubyonRails"), 'http://rubyonrails.org/' %>
   </small>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-fluid-top navbar-inner" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class='navbar-brand' href=<%= root_path %>><img src="/assets/iap_smartvending_logo.gif"></a>
    <ul class="nav navbar-nav navbar-right pull-right">
      <li><a href=<%= help_path %>> Help </a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> User <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if !user_signed_in? %><li><a  href=<%= new_user_session_path %>><i class="fa fa-sign-in"></i> Sign in </a></li><% end %>
          <% if user_signed_in? %>
             <li><a href=<%= destroy_user_session_path %>><i class="fa fa-sign-out"></i> Sign out </a></li>
             <li><a  href=<%= edit_user_registration_path %>><i class="fa fa-arrows-h"></i> Change Password </a></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='https://www.google.com/jsapi'></script>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>  
  </head>
  <body>
    <%= render 'layouts/header' %>  
    <%= javascript_include_tag "http://code.highcharts.com/highcharts.js", "chartkick" %> 
  <div class="container-fluid">
      <div class="row-fluid">
          <% if user_signed_in? %>
          <div class="span2">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <li><a href=<%= root_path %>> Dashboard </a>
                </li>
                <li><a data-no-turbolink="true" href=<%= machines_path %>> Machines </a>
                </li>
                <li><a href=<%= alarms_path %>> Alarms </a>
                </li>
                <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Graphics <b class="caret"></b></a>

                    <ul class="dropdown-menu" role="menu">
                    <li><a href=<%= graphics_esolar_path %>> Solar Energy Produced and Consumed </a></li>
                    <li><a href=<%= graphics_cnxtrasp_path %> > Direct Comanding </a></li>
                    <li><a href=<%= graphics_psimulado_path %>> Cost & Temperature Simulation </a></li>
                    <li class="divider"></li>
                   </ul>
                </li>
              </ul>
            </div><!--/.well -->
            <!-- Sidebar -->
          </div><!--/span-->
          <div class="span10">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div><!--/span-->
          <% end %>
          <% if !user_signed_in? %>
          <div class="row-fluid">
            <div class="span4 offset3">
              <%= yield %>
            </div>
            <div class="span4">
            </div>
          </div>
          <% end %>
      </div>
      <div class="row-fluid">
          <div class="span12">
             <div class="page-header">
             </div>
          </div>
      </div>
      <div class="row-fluid">
         <div class="span6"><%= render 'layouts/footer' %></div>
         <div class="span6"><%= render 'layouts/footer2' %></div>
      </div>
  </div> <!-- /container -->
  <%= yield :scripts %>
  </body>
</html>